import type { Metadata, Viewport } from "next";
import { ThemeProvider } from "next-themes";
import { Toaster } from "react-hot-toast";
import { ServiceWorkerRegister } from "@/components/ServiceWorkerRegister";
import { InstallPWAPrompt } from "@/components/InstallPWAPrompt";
import "./globals.css";

export const metadata: Metadata = {
  title: { default: "Duka by Awarizon", template: "%s | Duka" },
  description: "Discover and shop from verified Nigerian vendors — Duka by Awarizon",
  // Next auto-generates the <link rel="manifest"> from src/app/manifest.ts,
  // and the favicon/apple-touch-icon <link> tags from src/app/icon.png and
  // src/app/apple-icon.png — no manual wiring needed for those.
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Duka",
  },
};

export const viewport: Viewport = {
  themeColor: "#f97316",
  width: "device-width",
  initialScale: 1,
};

// iOS ignores the web manifest for splash screens entirely — it only reads
// these <link rel="apple-touch-startup-image"> tags, one per breakpoint,
// matched by the media query. Not exhaustive per-device-model coverage
// (dozens of exact pixel variants exist), just the common modern iPhone
// portrait sizes generated by scripts/generate-pwa-icons.mjs.
const APPLE_SPLASH_SCREENS = [
  { href: "/icons/splash-1170x2532.png", media: "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)" },
  { href: "/icons/splash-1179x2556.png", media: "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3)" },
  { href: "/icons/splash-1284x2778.png", media: "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3)" },
  { href: "/icons/splash-1290x2796.png", media: "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        {APPLE_SPLASH_SCREENS.map((screen) => (
          <link key={screen.href} rel="apple-touch-startup-image" href={screen.href} media={screen.media} />
        ))}
      </head>
      <body
        className="bg-zinc-50 dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100 min-h-screen"
        style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
        >
          {children}
          <ServiceWorkerRegister />
          <InstallPWAPrompt />
          <Toaster
            position="top-right"
            toastOptions={{
              style: {
                borderRadius: "12px",
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: "14px",
              },
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
